### ISSUE TITLE
2020 data

### ISSUE THREAD

**Issue by kylemcdonald** [GoogleCloudPlatform/region-carbon-info#1]
Hi! I can see that the 2019 data is currently available, but I'm looking for 2020 data. Is there any timeline for uploading the 2020 data, or any other years? Thank you 🙏

**Comment by steren** [comment]
Hi, we will hopefully publish the 2020 info within a few weeks.

**Comment by Asim-tech235** [comment]
Thank goodness

**Comment by mulhoon** [comment]
Hi @steren,
Any news on the 2020 data?

Many thanks

**Comment by steren** [comment]
We're finalizing the 2020 data
