### ISSUE TITLE
2022 & 2023 data

### ISSUE THREAD

**Issue by katrinleinweber** [GoogleCloudPlatform/region-carbon-info#7]
Hi @steren 👋 Is any data available for 2022 and the current year?

Thank you & kind regards!

**Comment by steren** [comment]
The data is usually released mid year for the previous year. I'll follow up for 2022.

**Comment by msts1906** [comment]
Are there any updates regarding the 2022 data? 
I need this for a study I'm conducting

**Comment by steren** [comment]
2022 data will be published once Google publishes its 2022 environmental report. Pretty soon.

**Comment by steren** [comment]
2022 data is now available at https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2022.csv

2023 will be published around the same date in 2024
