### ISSUE TITLE
No data for Doha (me-central1)

### ISSUE THREAD

**Issue by uri-rodberg** [GoogleCloudPlatform/region-carbon-info#8]
I checked https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2022.csv and I didn't find data for Doha (me-central1). Can you add it please?

**Comment by shuuji3** [comment]
The Doha region is relatively new and became available on March 2023 (https://cloud.google.com/run/docs/release-notes#March_30_2023) so I guess that's why it aren't included in the 2022 data.

**Comment by uri-rodberg** [comment]
> The Doha region is relatively new and became available on March 2023 (https://cloud.google.com/run/docs/release-notes#March_30_2023) so I guess that's why it aren't included in the 2022 data.

Yes but Turin (europe-west12) was also added in 2023 and it is on https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2022.csv.

**Comment by shuuji3** [comment]
Sorry, that's right. Let's wait for the response.

**Comment by steren** [comment]
This data only guarantees to cover regions available during the year of the dataset.

We were able to add Turin because it is on the same grid as Milan, but Doha needs more work. It will be covered in the 2024 dataset.

**Comment by uri-rodberg** [comment]
OK, thank you. I'm closing this issue for now.
